name: Build and Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-publish:
    name: Build and Publish TelecomFaker
    runs-on: ubuntu-latest
    # Set permissions needed for trusted publishing
    permissions:
      id-token: write  # Required for trusted publishing
      contents: read   # Required to checkout the code
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel setuptools
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pip install -e .
        python -m behave
        
    - name: Build package
      run: |
        python -m build
        
    - name: Check package
      run: |
        python -m twine check dist/*
        
    - name: Publish to PyPI
      if: github.event_name == 'release'
      # Use trusted publishing instead of token-based auth
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # No need for password when using trusted publishing
        # Just need to specify the PyPI repository
        repository-url: https://upload.pypi.org/legacy/ 